name: CI
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.6'
      - run: npm install -g npm@8
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm run test:ci
